### ISSUE TITLE
[Crash]: Registry Object not Present: illagerinvasion:alchemist

### ISSUE THREAD

**Issue by Kyrnterra** [Fuzss/illagerinvasion#14]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.0.2

### Notes (Required)

Crashes on startup.

Log linked: https://paste.ee/p/9QEyh

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin}
-- MOD illagerinvasion --
Details:
	Mod File: /E:/MultiMC/instances/New Realms/.minecraft/mods/IllagerInvasion-v3.0.2-1.18.2-Forge.jar
	Failure message: Illager Invasion (illagerinvasion) encountered an error during the construct event phase
		java.lang.NullPointerException: Registry Object not present: illagerinvasion:alchemist
	Mod Version: 3.0.2
	Mod Issue URL: https://github.com/Fuzss/illagerinvasion/issues
	Exception message: java.lang.NullPointerException: Registry Object not present: illagerinvasion:alchemist
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:320) ~[forge-1.18.2-40.2.7-universal.jar%23323!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,xf:fml:forge:registry_object_binary_compat}
	at fuzs.puzzleslib.impl.init.ForgeRegistryReference.get(ForgeRegistryReference.java:50) ~[PuzzlesLib-v3.5.8-1.18.2-Forge.jar%23246!/:3.5.8] {re:classloading}
	at fuzs.illagerinvasion.handler.VillagerGoalHandler$AvoidVillagerEnemy.addAcceptableDistance(VillagerGoalHandler.java:76) ~[IllagerInvasion-v3.0.2-1.18.2-Forge.jar%23160!/:3.0.2] {re:classloading}
	at fuzs.illagerinvasion.handler.VillagerGoalHandler.init(VillagerGoalHandler.java:59) ~[IllagerInvasion-v3.0.2-1.18.2-Forge.jar%23160!/:3.0.2] {re:classloading}
	at fuzs.illagerinvasion.IllagerInvasion.onConstructMod(IllagerInvasion.java:48) ~[IllagerInvasion-v3.0.2-1.18.2-Forge.jar%23160!/:3.0.2] {re:classloading}
	at fuzs.puzzleslib.impl.core.ForgeModConstructor.lambda$construct$0(ForgeModConstructor.java:36) ~[PuzzlesLib-v3.5.8-1.18.2-Forge.jar%23246!/:3.5.8] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
	at fuzs.puzzleslib.impl.core.ForgeModConstructor.construct(ForgeModConstructor.java:32) ~[PuzzlesLib-v3.5.8-1.18.2-Forge.jar%23246!/:3.5.8] {re:classloading}
	at fuzs.puzzleslib.impl.core.ForgeFactories.constructMod(ForgeFactories.java:23) ~[PuzzlesLib-v3.5.8-1.18.2-Forge.jar%23246!/:3.5.8] {re:classloading}
	at fuzs.puzzleslib.api.core.v1.ModConstructor.construct(ModConstructor.java:35) ~[PuzzlesLib-v3.5.8-1.18.2-Forge.jar%23246!/:3.5.8] {re:mixin,re:classloading}
	at fuzs.illagerinvasion.IllagerInvasionForge.onConstructMod(IllagerInvasionForge.java:18) ~[IllagerInvasion-v3.0.2-1.18.2-Forge.jar%23160!/:3.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_490_IllagerInvasionForge_onConstructMod_FMLConstructModEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.7.jar%23320!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.7.jar%23319!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

### Crash Report (Required)

https://paste.ee/p/9QEyh

**Comment by Fuzss** [comment]
Fixed in v3.0.3.
