### ISSUE TITLE
[Crash]: Illager Invasion entrypoint `main`by `illagerinvasion`

### ISSUE THREAD

**Issue by suerion** [Fuzss/illagerinvasion#54]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.0

### Minimal Setup

No

### Notes (Required)

```[14:39:08] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'illagerinvasion' at 'fuzs.illagerinvasion.fabric.IllagerInvasionFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IllegalStateException: Duplicate DefaultAttributes entry: entity.illagerinvasion.alchemist
        at fuzs.puzzleslib.fabric.impl.core.context.EntityAttributesCreateContextFabricImpl.registerEntityAttributes(EntityAttributesCreateContextFabricImpl.java:16) ~[PuzzlesLib-v21.1.3-1.21.1-Fabric.jar:?]
        at fuzs.illagerinvasion.IllagerInvasion.onEntityAttributeCreation(IllagerInvasion.java:103) ~[IllagerInvasion-v21.1.0-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricModConstructor.registerLoadingHandlers(FabricModConstructor.java:39) ~[PuzzlesLib-v21.1.3-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricModConstructor.construct(FabricModConstructor.java:23) ~[PuzzlesLib-v21.1.3-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricFactories.constructMod(FabricFactories.java:30) ~[PuzzlesLib-v21.1.3-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.api.core.v1.ModConstructor.construct(ModConstructor.java:36) ~[PuzzlesLib-v21.1.3-1.21.1-Fabric.jar:?]
        at fuzs.illagerinvasion.fabric.IllagerInvasionFabric.onInitialize(IllagerInvasionFabric.java:11) ~[IllagerInvasion-v21.1.0-1.21.1-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more```

### Crash Report (Required)

no crashreport created, only Crash on Log

### latest.log (Optional)

https://gist.github.com/suerion/99602ebee4fbe6d7905dd0ff18a0a229

**Comment by suerion** [comment]
@Fuzss  i think with an Fix on Puzzle lib, could be, that it work now, i will test more.

**Comment by Fuzss** [comment]
Yeah, it's fixed. Will close this, thanks for the reminder!
